# Generated by Django 5.2.16 on 2026-08-02 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0002_seed_request_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected'), ('READY_FOR_ASSIGNMENT', 'Ready for assignment'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('FULFILLED', 'Fulfilled')], db_index=True, default='SUBMITTED', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='servicing.requesttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'SUBMITTED')), models.Q(models.Q(('status', 'SUBMITTED'), _negated=True), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='servicerequest_review_fields_match_status', violation_error_message='reviewed_by and reviewed_at must be set if and only if the request has left SUBMITTED.'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), models.Q(('rejection_reason', ''), _negated=True)), models.Q(models.Q(('status', 'REJECTED'), _negated=True), ('rejection_reason', '')), _connector='OR'), name='servicerequest_rejection_reason_only_when_rejected', violation_error_message='rejection_reason must be non-empty if and only if the request is REJECTED.')],
            },
        ),
    ]
