# Generated by Django 5.2.16 on 2026-08-02 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0005_structured_service_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='servicing.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED'])), fields=('service_request',), name='assignment_one_live_per_request', violation_error_message='This request already has an assignment awaiting a response or accepted.'), models.CheckConstraint(condition=models.Q(models.Q(('responded_at__isnull', True), ('status', 'PENDING')), models.Q(models.Q(('status', 'PENDING'), _negated=True), ('responded_at__isnull', False)), _connector='OR'), name='assignment_responded_at_matches_status', violation_error_message='responded_at must be set if and only if the assignment has been accepted or declined.')],
            },
        ),
    ]
