# Generated by Django 5.2.16 on 2026-08-02 19:56

from django.conf import settings
from django.db import migrations, models


def backfill_started_at(apps, schema_editor):
    """Reconcile existing rows with the split of "accepted" from "started".

    Before this migration, accepting an assignment moved a request straight to
    IN_PROGRESS. Those rows were accepted, never commenced -- which is exactly
    what SCHEDULED now means, so that is where they belong.

    FULFILLED rows really were worked, so they need a started_at for the new
    constraint. scheduled_start is the best evidence available; the exact
    moment was never recorded because there was nothing to record it.

    Without this, AddConstraint below fails on any populated database.
    """
    ServiceRequest = apps.get_model("servicing", "ServiceRequest")

    ServiceRequest.objects.filter(status="IN_PROGRESS").update(status="SCHEDULED")
    ServiceRequest.objects.filter(
        status="FULFILLED", started_at__isnull=True
    ).update(started_at=models.F("scheduled_start"))


def unbackfill_started_at(apps, schema_editor):
    """Reverse: SCHEDULED did not exist before, so fold it back to IN_PROGRESS."""
    ServiceRequest = apps.get_model("servicing", "ServiceRequest")

    ServiceRequest.objects.filter(status="SCHEDULED").update(status="IN_PROGRESS")
    ServiceRequest.objects.update(started_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0006_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected'), ('READY_FOR_ASSIGNMENT', 'Ready for assignment'), ('ASSIGNED', 'Assigned'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('FULFILLED', 'Fulfilled')], db_index=True, default='SUBMITTED', max_length=30),
        ),
        # Must run BETWEEN the schema change and the constraint: the column has
        # to exist, and the rows have to be legal before the rule is imposed.
        migrations.RunPython(backfill_started_at, unbackfill_started_at),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('started_at__isnull', False), ('status__in', ['IN_PROGRESS', 'FULFILLED'])), models.Q(models.Q(('status__in', ['IN_PROGRESS', 'FULFILLED']), _negated=True), ('started_at__isnull', True)), _connector='OR'), name='servicerequest_started_at_matches_status', violation_error_message='started_at must be set if and only if the work has commenced.'),
        ),
    ]
